ACTION_CREATE_CHART = "create_chart"
ACTION_UPDATE_CHART = "update_chart"
ACTION_ERROR = "error"

ALLOWED_ACTION_TYPES = [ACTION_CREATE_CHART, ACTION_UPDATE_CHART, ACTION_ERROR]

ERROR_CODE_AGENT_NO_ACTION = "agent_no_action"
ERROR_CODE_CLARIFICATION_REQUIRED = "clarification_required"
ERROR_CODE_EXPLANATION = "explanation"
ERROR_CODE_HELP = "help"
ERROR_CODE_INVALID_ACTION = "invalid_action"
ERROR_CODE_OUT_OF_SCOPE = "out_of_scope"
ERROR_CODE_SMALLTALK = "smalltalk"
ERROR_CODE_VALIDATION_ERROR = "validation_error"
