CHART_TYPE_BAR = "bar"
CHART_TYPE_LINE = "line"
CHART_TYPE_PIE = "pie"
CHART_TYPE_TABLE = "table"

XY_CHART_TYPES = {CHART_TYPE_BAR, CHART_TYPE_LINE}

CHART_TYPE_LABELS = {
    CHART_TYPE_BAR: "柱状图",
    CHART_TYPE_LINE: "折线图",
    CHART_TYPE_PIE: "饼图",
    CHART_TYPE_TABLE: "表格",
}
