COLUMN_TYPE_STRING = "string"
COLUMN_TYPE_NUMBER = "number"
COLUMN_TYPE_DATE = "date"
COLUMN_TYPE_CURRENCY = "currency"
COLUMN_TYPE_PERCENT = "percent"

ALLOWED_COLUMN_TYPES = [
    COLUMN_TYPE_STRING,
    COLUMN_TYPE_NUMBER,
    COLUMN_TYPE_DATE,
    COLUMN_TYPE_CURRENCY,
    COLUMN_TYPE_PERCENT,
]

NUMERIC_COLUMN_TYPES = {
    COLUMN_TYPE_NUMBER,
    COLUMN_TYPE_CURRENCY,
    COLUMN_TYPE_PERCENT,
}
