INTENT_CREATE_CHART = "create_chart"
INTENT_UPDATE_STYLE = "update_style"
INTENT_UPDATE_DATA = "update_data"
INTENT_CHANGE_CHART_TYPE = "change_chart_type"
INTENT_EXPLAIN_CHART = "explain_chart"
INTENT_SMALLTALK = "smalltalk"
INTENT_HELP = "help"
INTENT_OUT_OF_SCOPE = "out_of_scope"
INTENT_UNCLEAR_CHART_REQUEST = "unclear_chart_request"
INTENT_UNKNOWN = "unknown"

TOOL_CREATE_CHART = "create_chart"
TOOL_UPDATE_STYLE = "update_style"
TOOL_UPDATE_DATA = "update_data"
TOOL_CHANGE_CHART_TYPE = "change_chart_type"
TOOL_ANSWER_CURRENT_CHART_QUESTION = "answer_current_chart_question"
TOOL_CLARIFY_CHART_REQUEST = "clarify_chart_request"
TOOL_SMALLTALK = "smalltalk"
TOOL_HELP = "help"
TOOL_OUT_OF_SCOPE = "out_of_scope"

CURRENT_CHART_TOOLS = {
    TOOL_UPDATE_STYLE,
    TOOL_UPDATE_DATA,
    TOOL_CHANGE_CHART_TYPE,
    TOOL_ANSWER_CURRENT_CHART_QUESTION,
}

DETERMINISTIC_EDIT_TOOLS = {
    TOOL_UPDATE_STYLE,
    TOOL_UPDATE_DATA,
    TOOL_CHANGE_CHART_TYPE,
}

TOOL_TO_INTENT = {
    TOOL_CREATE_CHART: INTENT_CREATE_CHART,
    TOOL_UPDATE_STYLE: INTENT_UPDATE_STYLE,
    TOOL_UPDATE_DATA: INTENT_UPDATE_DATA,
    TOOL_CHANGE_CHART_TYPE: INTENT_CHANGE_CHART_TYPE,
    TOOL_ANSWER_CURRENT_CHART_QUESTION: INTENT_EXPLAIN_CHART,
    TOOL_CLARIFY_CHART_REQUEST: INTENT_UNCLEAR_CHART_REQUEST,
    TOOL_SMALLTALK: INTENT_SMALLTALK,
    TOOL_HELP: INTENT_HELP,
    TOOL_OUT_OF_SCOPE: INTENT_OUT_OF_SCOPE,
}

AVAILABLE_TOOLS = [
    TOOL_CREATE_CHART,
    TOOL_UPDATE_STYLE,
    TOOL_UPDATE_DATA,
    TOOL_CHANGE_CHART_TYPE,
    TOOL_ANSWER_CURRENT_CHART_QUESTION,
    TOOL_CLARIFY_CHART_REQUEST,
    TOOL_SMALLTALK,
    TOOL_HELP,
    TOOL_OUT_OF_SCOPE,
]

SUPPORTED_INTENTS = [
    INTENT_CREATE_CHART,
    INTENT_UPDATE_STYLE,
    INTENT_UPDATE_DATA,
    INTENT_CHANGE_CHART_TYPE,
    INTENT_EXPLAIN_CHART,
    INTENT_SMALLTALK,
    INTENT_HELP,
    INTENT_OUT_OF_SCOPE,
    INTENT_UNCLEAR_CHART_REQUEST,
    INTENT_UNKNOWN,
]
