UI_BLOCK_METRIC_SUMMARY = "metric_summary"
UI_BLOCK_INSIGHT_CARD = "insight_card"
UI_BLOCK_SUGGESTED_ACTIONS = "suggested_actions"
UI_BLOCK_DATA_TABLE = "data_table"

ALLOWED_UI_BLOCK_TYPES = [
    UI_BLOCK_METRIC_SUMMARY,
    UI_BLOCK_INSIGHT_CARD,
    UI_BLOCK_SUGGESTED_ACTIONS,
    UI_BLOCK_DATA_TABLE,
]
